branches:
  only:
    - master

language: r
sudo: required
cran: http://cran.rstudio.com
latex: false
pandoc: true
warnings_are_errors: false
cache:
  directories:
  - $HOME/.local/share/renv
  - $TRAVIS_BUILD_DIR/renv/library
  - $HOME/.TinyTeX/

env:
  - BOOKDOWN_FORMAT=SITE
  - BOOKDOWN_FORMAT=PDF

r:
  - release

before_install:
  - sudo apt-get install -y libgit2-dev libxml2-dev libssl-dev
  - sudo apt-get install -y libcurl4-openssl-dev libmagick++-dev
  - sudo apt-get install -y texlive-extra-utils ghostscript

install:
  - cd .. && Rscript -e "install.packages('tinytex')"
  - Rscript -e "tinytex::install_tinytex()"
  - export PATH=$HOME/bin:${PATH}
  - cd $TRAVIS_BUILD_DIR && Rscript -e "renv::restore()"
  # this shouldn't be necessary but renv sometimes installs the wrong version
  # of sl3 (from master) in its attempts to repair the dependency tree
  - cd $TRAVIS_BUILD_DIR && Rscript -e "renv::install('tlverse/sl3@devel')"

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - travis_wait 120 ./_build.sh
  - test $TRAVIS_BRANCH = "master" && ./_deploy.sh

notifications:
  email:
    on_success: change
    on_failure: change
